apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: akdevopscoaching/mywebapp
        name: springboot
        ports:
        - containerPort: 8085
